"""
Backtesting engine for AgentICTrader.AI.

Replays historical setups in strict candle_time order (no look-ahead bias).
Applies confidence threshold gates and simulates trades.

Confidence thresholds (from design.md):
  < 0.65  → DISCARD (no trade, not logged)
  0.65–0.74 → LOG ONLY (no trade simulated)
  0.75–0.84 → NOTIFY (trade simulated)
  ≥ 0.85  → NOTIFY + AUTO-EXECUTE (trade simulated)

Risk rule (FR-7):
  position_size = (equity * risk_pct) / sl_distance
  sl_distance   = abs(entry_price - sl_price)
  max risk per trade = 1% of account equity

Metrics returned in BacktestResult:
  - sharpe_ratio      : annualised Sharpe (mean_return / std_return) * sqrt(252)
  - sortino_ratio     : annualised Sortino (mean_return / downside_std) * sqrt(252)
  - max_drawdown_pct  : maximum peak-to-trough drawdown as a percentage
  - win_rate          : wins / total_trades
  - avg_r_multiple    : mean R-multiple across all trades
  - expectancy        : (win_rate * avg_win_r) - (loss_rate * avg_loss_r)
  - trade_count       : total number of simulated trades
  - total_pnl         : final_equity - initial_equity
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List, Optional

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Confidence threshold gates
THRESHOLD_DISCARD: float = 0.65   # below this → discard entirely
THRESHOLD_LOG_ONLY: float = 0.75  # [0.65, 0.75) → log only, no trade
# >= 0.75 → simulate trade

# Risk parameters
DEFAULT_RISK_PCT: float = 0.01    # 1% of equity per trade
DEFAULT_EQUITY: float = 10_000.0

# Annualisation factor (trading days per year)
ANNUALISATION_FACTOR: float = math.sqrt(252)


# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class Setup:
    """
    A single trade setup generated by the ML pipeline.

    Attributes:
        instrument      : Trading instrument (e.g. "EURUSD")
        timeframe       : Candle timeframe (e.g. "M5")
        candle_time     : UTC timestamp of the candle that generated this setup.
                          Used for strict time-ordering (no look-ahead).
        confidence_score: Confluence score in [0.0, 1.0]
        entry_price     : Proposed entry price
        sl_price        : Stop-loss price
        tp_price        : Take-profit price
        outcome         : Optional pre-determined outcome ("WIN" | "LOSS").
                          If None, defaults to "WIN" for backtesting purposes.
    """

    instrument: str
    timeframe: str
    candle_time: datetime
    confidence_score: float
    entry_price: float
    sl_price: float
    tp_price: float
    outcome: Optional[str] = None


@dataclass
class TradeRecord:
    """
    Record of a single simulated trade.

    Attributes:
        setup           : The originating Setup
        entry_time      : Time the trade was entered (== setup.candle_time)
        position_size   : Computed position size (units)
        r_multiple      : Realised R-multiple (+ve for win, -ve for loss)
        pnl             : Profit/loss in account currency
        outcome         : "WIN" or "LOSS"
    """

    setup: Setup
    entry_time: datetime
    position_size: float
    r_multiple: float
    pnl: float
    outcome: str


@dataclass
class BacktestResult:
    """
    Aggregated results from a backtest run.

    Attributes:
        trade_count     : Total number of simulated trades
        total_pnl       : final_equity - initial_equity
        win_rate        : wins / trade_count  (0.0 if no trades)
        avg_r_multiple  : Mean R-multiple across all trades
        expectancy      : (win_rate * avg_win_r) - (loss_rate * avg_loss_r)
        max_drawdown_pct: Maximum peak-to-trough drawdown as a percentage
        sharpe_ratio    : Annualised Sharpe ratio (0.0 if std == 0 or no trades)
        sortino_ratio   : Annualised Sortino ratio (0.0 if downside_std == 0 or no trades)
        trades          : List of individual TradeRecord objects
        log_only_setups : Setups that were logged but not traded (0.65 <= conf < 0.75)
    """

    trade_count: int
    total_pnl: float
    win_rate: float
    avg_r_multiple: float
    expectancy: float
    max_drawdown_pct: float
    sharpe_ratio: float
    sortino_ratio: float
    trades: List[TradeRecord] = field(default_factory=list)
    log_only_setups: List[Setup] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class BacktestEngine:
    """
    Backtesting engine that replays setups in strict time order.

    Usage::

        engine = BacktestEngine(initial_equity=10_000.0)
        result = engine.run(setups)

    Args:
        initial_equity: Starting account equity (default 10 000.0)
        risk_pct      : Fraction of equity risked per trade (default 0.01 = 1%)
    """

    def __init__(
        self,
        initial_equity: float = DEFAULT_EQUITY,
        risk_pct: float = DEFAULT_RISK_PCT,
    ) -> None:
        self.initial_equity = initial_equity
        self.risk_pct = risk_pct

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self, setups: List[Setup]) -> BacktestResult:
        """
        Run the backtest over the provided setups.

        Setups are sorted by candle_time ascending before processing to
        guarantee strict time order and eliminate any look-ahead bias.

        Args:
            setups: List of Setup objects (order does not matter — engine sorts them)

        Returns:
            BacktestResult with all computed metrics
        """
        if not setups:
            return self._empty_result()

        # ── 1. Sort by candle_time ascending (strict time order, no look-ahead) ──
        ordered = sorted(setups, key=lambda s: s.candle_time)

        equity = self.initial_equity
        equity_curve: List[float] = [equity]
        trades: List[TradeRecord] = []
        log_only: List[Setup] = []

        # ── 2. Process each setup in time order ──────────────────────────────────
        for setup in ordered:
            conf = setup.confidence_score

            if conf < THRESHOLD_DISCARD:
                # DISCARD — below hard floor, not even logged
                continue

            if conf < THRESHOLD_LOG_ONLY:
                # LOG ONLY — record but do not simulate a trade
                log_only.append(setup)
                continue

            # SIMULATE TRADE (conf >= 0.75)
            trade = self._simulate_trade(setup, equity)
            trades.append(trade)
            equity += trade.pnl
            equity_curve.append(equity)

        # ── 3. Compute aggregate metrics ─────────────────────────────────────────
        return self._compute_result(
            trades=trades,
            log_only=log_only,
            equity_curve=equity_curve,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _simulate_trade(self, setup: Setup, current_equity: float) -> TradeRecord:
        """
        Simulate a single trade from a setup.

        Position size is computed as:
            position_size = (equity * risk_pct) / sl_distance

        R-multiple:
            For a BUY (tp > entry > sl):
                r_multiple = (tp - entry) / (entry - sl)  on WIN
                r_multiple = -1.0                          on LOSS
            For a SELL (tp < entry < sl):
                r_multiple = (entry - tp) / (sl - entry)  on WIN
                r_multiple = -1.0                          on LOSS

        PnL:
            pnl = r_multiple * (current_equity * risk_pct)

        Args:
            setup         : The Setup to simulate
            current_equity: Current account equity at time of trade

        Returns:
            TradeRecord with all computed fields
        """
        sl_distance = abs(setup.entry_price - setup.sl_price)

        # Guard against zero SL distance (degenerate setup)
        if sl_distance < 1e-10:
            sl_distance = 1e-10

        position_size = (current_equity * self.risk_pct) / sl_distance

        # Determine trade direction
        is_buy = setup.tp_price > setup.entry_price

        # Compute R-multiple based on direction
        if is_buy:
            r_win = (setup.tp_price - setup.entry_price) / (setup.entry_price - setup.sl_price)
        else:
            r_win = (setup.entry_price - setup.tp_price) / (setup.sl_price - setup.entry_price)

        # Determine outcome (default to WIN if not specified)
        outcome = (setup.outcome or "WIN").upper()

        if outcome == "WIN":
            r_multiple = r_win
        else:
            r_multiple = -1.0

        # PnL in account currency
        risk_amount = current_equity * self.risk_pct
        pnl = r_multiple * risk_amount

        return TradeRecord(
            setup=setup,
            entry_time=setup.candle_time,
            position_size=position_size,
            r_multiple=r_multiple,
            pnl=pnl,
            outcome=outcome,
        )

    def _compute_result(
        self,
        trades: List[TradeRecord],
        log_only: List[Setup],
        equity_curve: List[float],
    ) -> BacktestResult:
        """
        Compute all aggregate metrics from the list of trades.

        Args:
            trades      : List of simulated TradeRecord objects
            log_only    : Setups that were logged but not traded
            equity_curve: Equity values after each trade (including initial)

        Returns:
            BacktestResult with all metrics populated
        """
        n = len(trades)

        if n == 0:
            return BacktestResult(
                trade_count=0,
                total_pnl=0.0,
                win_rate=0.0,
                avg_r_multiple=0.0,
                expectancy=0.0,
                max_drawdown_pct=0.0,
                sharpe_ratio=0.0,
                sortino_ratio=0.0,
                trades=[],
                log_only_setups=log_only,
            )

        # ── Win rate ─────────────────────────────────────────────────────────────
        wins = [t for t in trades if t.outcome == "WIN"]
        losses = [t for t in trades if t.outcome != "WIN"]
        win_rate = len(wins) / n

        # ── R-multiples ──────────────────────────────────────────────────────────
        r_multiples = [t.r_multiple for t in trades]
        avg_r_multiple = sum(r_multiples) / n

        # ── Expectancy ───────────────────────────────────────────────────────────
        win_rs = [t.r_multiple for t in wins]
        loss_rs = [abs(t.r_multiple) for t in losses]

        avg_win_r = sum(win_rs) / len(win_rs) if win_rs else 0.0
        avg_loss_r = sum(loss_rs) / len(loss_rs) if loss_rs else 0.0
        loss_rate = 1.0 - win_rate
        expectancy = (win_rate * avg_win_r) - (loss_rate * avg_loss_r)

        # ── Total PnL ────────────────────────────────────────────────────────────
        total_pnl = equity_curve[-1] - equity_curve[0]

        # ── Max drawdown ─────────────────────────────────────────────────────────
        max_drawdown_pct = self._compute_max_drawdown(equity_curve)

        # ── Returns per trade (as fraction of equity at start of each trade) ─────
        # Use PnL / initial_equity as a simple per-trade return proxy
        returns = [t.pnl / self.initial_equity for t in trades]

        # ── Sharpe ratio ─────────────────────────────────────────────────────────
        sharpe_ratio = self._compute_sharpe(returns)

        # ── Sortino ratio ────────────────────────────────────────────────────────
        sortino_ratio = self._compute_sortino(returns)

        return BacktestResult(
            trade_count=n,
            total_pnl=total_pnl,
            win_rate=win_rate,
            avg_r_multiple=avg_r_multiple,
            expectancy=expectancy,
            max_drawdown_pct=max_drawdown_pct,
            sharpe_ratio=sharpe_ratio,
            sortino_ratio=sortino_ratio,
            trades=trades,
            log_only_setups=log_only,
        )

    @staticmethod
    def _compute_max_drawdown(equity_curve: List[float]) -> float:
        """
        Compute maximum peak-to-trough drawdown as a percentage.

        Args:
            equity_curve: List of equity values (including initial equity)

        Returns:
            Maximum drawdown as a percentage (0.0 to 100.0)
        """
        if len(equity_curve) < 2:
            return 0.0

        peak = equity_curve[0]
        max_dd = 0.0

        for value in equity_curve[1:]:
            if value > peak:
                peak = value
            drawdown = (peak - value) / peak * 100.0
            if drawdown > max_dd:
                max_dd = drawdown

        return max_dd

    @staticmethod
    def _mean(values: List[float]) -> float:
        """Compute arithmetic mean of a list."""
        if not values:
            return 0.0
        return sum(values) / len(values)

    @staticmethod
    def _std(values: List[float], mean: float) -> float:
        """Compute population standard deviation."""
        if len(values) < 2:
            return 0.0
        variance = sum((v - mean) ** 2 for v in values) / len(values)
        return math.sqrt(variance)

    def _compute_sharpe(self, returns: List[float]) -> float:
        """
        Compute annualised Sharpe ratio.

        sharpe = (mean_return / std_return) * sqrt(252)

        Returns 0.0 if std == 0 or no returns.

        Args:
            returns: Per-trade returns as fractions of initial equity

        Returns:
            Annualised Sharpe ratio
        """
        if not returns:
            return 0.0

        mean_r = self._mean(returns)
        std_r = self._std(returns, mean_r)

        if std_r == 0.0:
            return 0.0

        return (mean_r / std_r) * ANNUALISATION_FACTOR

    def _compute_sortino(self, returns: List[float]) -> float:
        """
        Compute annualised Sortino ratio.

        sortino = (mean_return / downside_std) * sqrt(252)

        Downside std uses only negative returns (below 0).
        Returns 0.0 if downside_std == 0 or no returns.

        Args:
            returns: Per-trade returns as fractions of initial equity

        Returns:
            Annualised Sortino ratio
        """
        if not returns:
            return 0.0

        mean_r = self._mean(returns)
        downside = [r for r in returns if r < 0.0]

        if not downside:
            return 0.0

        downside_mean = self._mean(downside)
        downside_std = self._std(downside, downside_mean)

        if downside_std == 0.0:
            return 0.0

        return (mean_r / downside_std) * ANNUALISATION_FACTOR

    @staticmethod
    def _empty_result() -> BacktestResult:
        """Return an empty BacktestResult for when no setups are provided."""
        return BacktestResult(
            trade_count=0,
            total_pnl=0.0,
            win_rate=0.0,
            avg_r_multiple=0.0,
            expectancy=0.0,
            max_drawdown_pct=0.0,
            sharpe_ratio=0.0,
            sortino_ratio=0.0,
            trades=[],
            log_only_setups=[],
        )
